/* constants for saving the student */
export const TEACHER_SAVE_REQUEST = "TEACHER_SAVE_REQUEST";
export const TEACHER_SAVE_SUCCESS = "TEACHER_SAVE_SUCCESS";
export const TEACHER_SAVE_FAIL = "TEACHER_SAVE_FAIL";

export const TEACHER_LIST_REQUEST = "TEACHER_LIST_REQUEST";
export const TEACHER_LIST_SUCCESS = "TEACHER_LIST_SUCCESS";
export const TEACHER_LIST_FAIL = "TEACHER_LIST_FAIL";

export const TEACHER_DATA_REQUEST = "TEACHER_DATA_REQUEST";
export const TEACHER_DATA_SUCCESS = "TEACHER_DATA_SUCCESS";
export const TEACHER_DATA_FAIL = "TEACHER_DATA_FAIL";

export const TEACHER_DELETED_REQUEST = "TEACHER_DELETED_REQUEST";
export const TEACHER_DELETED_SUCCESS = "TEACHER_DELETED_SUCCESS";
export const TEACHER_DELETED_FAIL = "TEACHER_DELETED_FAIL";

/* constants for getting the teacher list at pariticular classes */
export const CLASS_TEACHER_LIST_REQUEST = "CLASS_TEACHER_LIST_REQUEST";
export const CLASS_TEACHER_LIST_SUCCESS = "CLASS_TEACHER_LIST_SUCCESS";
export const CLASS_TEACHER_LIST_FAIL = "CLASS_TEACHER_LIST_FAIL";

export const TEACHERS_LENGTH_REQUEST = "TEACHERS_LENGTH_REQUEST";
export const TEACHERS_LENGTH_SUCCESS = "TEACHERS_LENGTH_SUCCESS";
export const TEACHERS_LENGTH_FAIL = "TEACHERS_LENGTH_FAIL";
